import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Login from "@/components/Login";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { user } = Login;
  if (!Login) {
    return <Link href="/" />;
  }
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
